//Authentication
//Login
export const AUTHLOGIN_SUCCESS = "AUTHLOGIN_SUCCESS";
export const AUTHLOGIN_ERROR = "AUTHLOGIN_ERROR";

//Dashboard
//Get Dashboard Data
export const GET_DASHBOARD_DATA_LOADING = "GET_DASHBOARD_DATA_LOADING";
export const GET_DASHBOARD_DATA_SUCCESS = "GET_DASHBOARD_DATA_SUCCESS";
export const GET_DASHBOARD_DATA_ERROR = "GET_DASHBOARD_DATA_ERROR";

//Display
//Get All List Display
export const ALL_LIST_DISPLAY_LOADING = "ALL_LIST_DISPLAY_LOADING";
export const ALL_LIST_DISPLAY_SUCCESS = "ALL_LIST_DISPLAY_SUCCESS";
export const ALL_LIST_DISPLAY_ERROR = "ALL_LIST_DISPLAY_ERROR";
//Get Display Details
export const GET_DISPLAY_DETAILS_LOADING = "GET_DISPLAY_DETAILS_LOADING";
export const GET_DISPLAY_DETAILS_SUCCESS = "GET_DISPLAY_DETAILS_SUCCESS";
export const GET_DISPLAY_DETAILS_ERROR = "GET_DISPLAY_DETAILS_ERROR";

//Routes
//Get All List Routes
export const ALL_LIST_ROUTES_LOADING = "ALL_LIST_ROUTES_LOADING";
export const ALL_LIST_ROUTES_SUCCESS = "ALL_LIST_ROUTES_SUCCESS";
export const ALL_LIST_ROUTES_ERROR = "ALL_LIST_ROUTES_ERROR";
//Get Route Details
export const GET_ROUTE_DETAILS_LOADING = "GET_ROUTE_DETAILS_LOADING";
export const GET_ROUTE_DETAILS_SUCCESS = "GET_ROUTE_DETAILS_SUCCESS";
export const GET_ROUTE_DETAILS_ERROR = "GET_ROUTE_DETAILS_ERROR";

//Users
//Get All List Users
export const ALL_LIST_USERS_LOADING = "ALL_LIST_USERS_LOADING";
export const ALL_LIST_USERS_SUCCESS = "ALL_LIST_USERS_SUCCESS";
export const ALL_LIST_USERS_ERROR = "ALL_LIST_USERS_ERROR";
//Get User Details
export const GET_USER_DETAILS_LOADING = "GET_USER_DETAILS_LOADING";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_ERROR = "GET_USER_DETAILS_ERROR";
export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";
//Get User Spirit Meter
export const GET_USER_SPIRITMETER_SUCCESS = "GET_USER_SPIRITMETER_SUCCESS";
export const GET_USER_SPIRITMETER_ERROR = "GET_USER_SPIRITMETER_ERROR";
//Get User Display
export const GET_USER_DISPLAY_SUCCESS = " GET_USER_DISPLAY_SUCCESS";
export const GET_USER_DISPLAY_ERROR = " GET_USER_DISPLAY_ERROR";
//Get User Route
export const GET_USER_ROUTE_SUCCESS = " GET_USER_ROUTE_SUCCESS";
export const GET_USER_ROUTE_ERROR = " GET_USER_ROUTE_ERROR";
//Add User
export const ADD_USER_SUCCESS = " ADD_USER_SUCCESS";
export const ADD_USER_ERROR = " ADD_USER_ERROR";
//Delete User
export const DELETE_USER_SUCCESS = " DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = " DELETE_USER_ERROR";
