//Display
//Get All List Display
export const ALL_LIST_DISPLAY_LOADING = "ALL_LIST_DISPLAY_LOADING";
export const ALL_LIST_DISPLAY_SUCCESS = "ALL_LIST_DISPLAY_SUCCESS";
export const ALL_LIST_DISPLAY_ERROR = "ALL_LIST_DISPLAY_ERROR";
