//Authentication
//Login
export const AUTHLOGIN_SUCCESS = "AUTHLOGIN_SUCCESS";
export const AUTHLOGIN_ERROR = "AUTHLOGIN_ERROR";

//Display
//Get All List Display
export const ALL_LIST_DISPLAY_LOADING = "ALL_LIST_DISPLAY_LOADING";
export const ALL_LIST_DISPLAY_SUCCESS = "ALL_LIST_DISPLAY_SUCCESS";
export const ALL_LIST_DISPLAY_ERROR = "ALL_LIST_DISPLAY_ERROR";
//Get Display Details
export const GET_DISPLAY_DETAILS_LOADING = "GET_DISPLAY_DETAILS_LOADING";
export const GET_DISPLAY_DETAILS_SUCCESS = "GET_DISPLAY_DETAILS_SUCCESS";
export const GET_DISPLAY_DETAILS_ERROR = "GET_DISPLAY_DETAILS_ERROR";

//Routes
//Get All List Routes
export const ALL_LIST_ROUTES_LOADING = "ALL_LIST_ROUTES_LOADING";
export const ALL_LIST_ROUTES_SUCCESS = "ALL_LIST_ROUTES_SUCCESS";
export const ALL_LIST_ROUTES_ERROR = "ALL_LIST_ROUTES_ERROR";
//Get Route Details
export const GET_ROUTE_DETAILS_LOADING = "GET_ROUTE_DETAILS_LOADING";
export const GET_ROUTE_DETAILS_SUCCESS = "GET_ROUTE_DETAILS_SUCCESS";
export const GET_ROUTE_DETAILS_ERROR = "GET_ROUTE_DETAILS_ERROR";

//Users
//Get All List Users
export const ALL_LIST_USERS_LOADING = "ALL_LIST_USERS_LOADING";
export const ALL_LIST_USERS_SUCCESS = "ALL_LIST_USERS_SUCCESS";
export const ALL_LIST_USERS_ERROR = "ALL_LIST_USERS_ERROR";
